version: '3'

services:
#  web:
#    image: richarvey/nginx-php-fpm
#    env_file:
#            - attlaz.env
#    ports:
#      - "80:80"
#    networks:
#          - frontend
#    volumes:
#          - ./web:/var/www/html
  api:
    image: attlaz/api:0.0.1
    build: ./api
    env_file:
        - attlaz.env
    networks:
          - frontend
          - backend
    ports:
          - "80:80"
    volumes:
          - ./api:/var/www/html
          - ./src:/var/www/src
    depends_on:
            - queue

  queue:
    image: rabbitmq:3-management
    env_file:
            - attlaz.env
    ports:
      - "32769:15672"
      - "5672:5672"
    networks:
          - backend
    deploy:
          replicas: 1
          update_config:
            parallelism: 2
            delay: 10s

  worker:
      image: attlaz/worker:0.0.1
      build: ./worker
      env_file:
              - attlaz.env
      networks:
                - backend
      deploy:
                replicas: 1
                update_config:
                  parallelism: 2
                  delay: 10s
      volumes:
          - ./worker:/var/attlaz
          - ./src:/var/src
      depends_on:
        - queue
networks:
  frontend:
    internal: false
  backend:
    internal: false